version: "3.9"

services:
  main-web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: scrapyd
    volumes:
      - C:\Users\Denze\Projects\remindMe:/remind_me
    ports: 
      - 8000
      - 8080:6800
    
    