version: "3.9"

services:
  web:
    build: .\web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .\web:/usr/src/remindme_web
    ports: 
      - 8000:8000

  scrapy:
    build: .\scraper
    command: scrapyd
    volumes:
      - .\scraper\:/usr/src/scraper/
    ports: 
      - 8080:8080
    depends_on:
      - web

  celery-worker:
    build: .\default\python\
    command: celery -A remind_me_django worker --without-heartbeat --without-gossip --without-mingle 
    volumes:
      - .\web\remind_me_django\:/usr/src/app/
    depends_on:
      - web
      - scrapy
    
  celery-worker:
    build: .\default\python\
    command: celery -A remind_me_django worker --without-heartbeat --without-gossip --without-mingle 
    volumes:
      - .\web\remind_me_django\:/usr/src/app/
    depends_on:
      - web
      - scrapy

  celery-beat:
    build: .\default\python\
    command: celery -A remind_me_django beat
    volumes:
      - .\web\remind_me_django\:/usr/src/app/
    depends_on:
      - celery-worker


    
  


    
      