version: "3.3"
# windows

services:
  web:
    build:
      context: .\web\remind_me_django\
      dockerfile: Dockerfile.web
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn --bind :8000 --workers 3 remind_me_django.wsgi:application
    # command: gunicorn remind_me_django.wsgi:application  --bind 0.0.0.0:$PORT 
    volumes:
      - .\web\remind_me_django\:/usr/src/remind_me_django/
    ports: 
      - 8000:8000
    container_name: web

  scrapy:
    build:
      context: .\scraper\
      dockerfile: Dockerfile.scraper
      
    # volumes:
    #   - .\scraper\:/usr/src/scraper/
    #   - .\scraper\etc\scrapyd\:/etc/scrapyd
    ports: 
      - 8080:8080
    container_name: scrapy
      
    
  celery:
    restart: always
    build: 
      context: .\web\remind_me_django
      dockerfile: Dockerfile.celery
    # --uid=nobody --gid=nogroup
    # volumes:
    #   - .\web\remind_me_django\:/usr/src/remind_me_django/
    container_name: celery
    depends_on:
      - web
      - scrapy