FROM python:3.9

ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/remind_me_django

COPY . .
RUN export PYTHONPATH=/usr/src/remind_me_django/
RUN pip install -r requirements.txt
RUN pip install psycopg2-binary
# RUN chown nobody:nogroup celerybeat-schedule

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "nano"]

CMD gunicorn remind_me_django.wsgi:application  --bind 0.0.0.0:$PORT 