# Generated by Django 3.2.5 on 2021-08-30 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_product_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_added']},
        ),
    ]
