# Generated by Django 3.2.5 on 2021-10-14 23:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210830_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 23, 25, 20, 13103, tzinfo=utc)),
        ),
    ]
